package com.qwill.app.realtime

object SocketEvent {
    const val MESSAGE_SEND = "message:send"
    const val MESSAGE_NEW = "message:new"
    const val MESSAGE_EDIT = "message:edit"
    const val MESSAGE_UPDATED = "message:updated"
    const val MESSAGE_DELETE = "message:delete"
    const val MESSAGE_DELETED = "message:deleted"
    const val MESSAGE_DELETE_BATCH = "message:deleteBatch"
    const val MESSAGE_DELETED_BATCH = "message:deletedBatch"
    const val MESSAGE_FORWARD = "message:forward"
    const val MESSAGE_REACT = "message:react"
    const val MESSAGE_REACTION = "message:reaction"
    const val CHAT_CREATED = "chat:created"
    const val CHAT_DELETED = "chat:deleted"
    const val CHAT_READ = "chat:read"
    const val CHAT_PIN = "chat:pin"
    const val CHAT_PINNED = "chat:pinned"
    const val TYPING_START = "typing:start"
    const val TYPING_STOP = "typing:stop"
    const val USER_TYPING = "user:typing"
    const val USER_PRESENCE = "user:presence"
    const val CHAT_UPDATED = "chat:updated"
    const val CHAT_BLOCK = "chat:block"
    const val MEMBER_CHANGED = "member:changed"
    const val VISIBILITY_CHANGE = "visibility:change"
    const val CALL_START = "call:start"
    const val CALL_INVITE = "call:invite"
    const val CALL_ACCEPT = "call:accept"
    const val CALL_DECLINE = "call:decline"
    const val CALL_LEAVE = "call:leave"
    const val CALL_ENDED = "call:ended"
    const val CALL_PARTICIPANT_CHANGED = "call:participantChanged"
    const val CALL_TAKEN_ELSEWHERE = "call:takenElsewhere"
    const val CALL_LIVE = "call:live"
}
